export const USER_LOGIN_SUCCESS = "USER_LOGIN";
export const USER_LOGIN_FAIL = "USER_FAIL";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT";

export const USER_REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_REGISTER_REQUEST = "REGISTER_REQUEST";
export const USER_REGISTER_FAIL = "REGISTER_FAIL";
